### ISSUE TITLE
Integration with https://github.com/tuvistavie/elixir-temp/

### ISSUE THREAD

**Issue by mwgkgk** [ericmj/true_story#3]
There's a `Temp.cleanup` function that can to be called to clean all temporary files created earlier. I've tried running it inside a story element, or as an `on_exit` callback to various things, as well as changing `Temp.track!` invocation point, but I can't get them to exist in the same universe: `Temp.tracked` shows nothing by the time we get to cleanup.

Basically the question is, how to use setup/teardown with TrueStory? On a side note I love the approach, it is subtle but changes the way you think about tests. Sort of pressures the user into structuring the tests better.

**Comment by ericmj** [comment]
Can you show the code you tried? Using setup and on_exit callbacks still works to true_story since it compiles to normal exunit tests in the end.

**Comment by mwgkgk** [comment]
Makes sense. Yes, it's probably specific to Temp. Thank you.

Since the filename explicitly existed in the context scope I just cleaned it up with File.rm, which is even better because it's explicit, and, testable :)
